app:
  name: @applicationName@
  version: @version@
  requireHttps: ${REQUIRE_HTTPS:false}
  front:
    origins: ${FRONT_ORIGINS:"http://localhost:3000"}
spring:
  application:
    name: lg-state-webgateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwkSetUri: ${JWK_SET_URI:http://localhost:8090/oauth2/jwks}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: ${WEB_GATEWAY_PORT:8100}
  tomcat:
    threads:
      max: ${MAX_THREAD:200}       # 最大スレッド数（デフォルト: 200）
      min-spare: ${MIN_THREAD:10}   # 最小アイドルスレッド数（デフォルト: 10）
    connection-timeout: ${CONNECTION_TIMEOUT:20000} # 接続タイムアウト（デフォルト: 20000）
    accept-count: ${ACCEPT_COUNT:100} # バックログ数（デフォルト: 100）
springdoc:
  swaggerUi:
    path: /swagger-ui.html
management:
  endpoints:
    web:
      exposure:
        include: "*"
grpc:
  client:
    jobService:
      address: dns:///${JOB_SERVICE_HOST:localhost}:${JOB_SERVICE_GRPC_PORT:9100}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: PLAINTEXT
      keep-alive-time: 600
      keep-alive-timeout: 60
      max-inbound-message-size: 52428800
    userProfileService:
      address: dns:///${USER_PROFILE_SERVICE_HOST:localhost}:${USER_PROFILE_SERVICE_GRPC_PORT:9080}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: PLAINTEXT
      keep-alive-time: 600
      keep-alive-timeout: 60
      max-inbound-message-size: 52428800
    userPreferenceService:
      address: dns:///${USER_PREFERENCE_SERVICE_HOST:localhost}:${USER_PREFERENCE_SERVICE_GRPC_PORT:9070}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: PLAINTEXT
      keep-alive-time: 600
      keep-alive-timeout: 60
      max-inbound-message-size: 52428800
    organizationService:
      address: dns:///${ORGANIZATION_SERVICE_HOST:localhost}:${ORGANIZATION_SERVICE_GRPC_PORT:9060}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: PLAINTEXT
      keep-alive-time: 600
      keep-alive-timeout: 60
      max-inbound-message-size: 52428800
    teamService:
      address: dns:///${TEAM_SERVICE_HOST:localhost}:${TEAM_SERVICE_GRPC_PORT:9050}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: PLAINTEXT
      keep-alive-time: 600
      keep-alive-timeout: 60
      max-inbound-message-size: 52428800
    storageService:
        address: dns:///${STORAGE_SERVICE_HOST:localhost}:${STORAGE_SERVICE_GRPC_PORT:9040}
        enableKeepAlive: true
        keepAliveWithoutCalls: true
        negotiationType: PLAINTEXT
        keep-alive-time: 600
        keep-alive-timeout: 60
        max-inbound-message-size: 52428800
    planService:
      address: dns:///${PLAN_SERVICE_HOST:localhost}:${PLAN_SERVICE_GRPC_PORT:9030}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: PLAINTEXT
      keep-alive-time: 600
      keep-alive-timeout: 60
      max-inbound-message-size: 52428800
